name: run python

on: push

jobs:
  python-code-run:
    name: python code test
    runs-on: ubuntu-latest
    steps:    
      - name: checkout code
        uses: actions/checkout@v4
        with: 
          repository: gsm34/test-actions
          ref: main
          path: splunk-api

      - name: read csv and call splunk API
        run:
          python splunk-api/readfile.py
