name: run python

on: 
  workflow_dispatch:
  
jobs:
  python-code-run:
    name: python code test
    runs-on: generic
    steps: 
      - uses: actions/checkout@v4
      - name: custom - read csv and call splunk API
        run:
          python readfile.py
