name: run python secret

on: 
  workflow_dispatch:
  
jobs:
  python-code-sec-run:
    name: python secret test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - python secret
        env: 
            API_KEY: ${{ secrets.API_KEY }}
        run:
          python python_secrets.py
