name: run curl

on: 
  workflow_dispatch:
jobs:
  curl-run:
    name: curl command
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - run curl command
        run:
          curl -sk --request POST https://thehartford.splunkcloud.com:8089/services -H "Authorization: Bearer testing1234"
