name: run python ver

on: 
  workflow_dispatch:
  
jobs:
  python-code-run:
    name: python code test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - python ver
        run: |
          python -c "import sys; print (sys.version)"
          id -u
          echo $UID
      - name: custom - python pip
        run:
          pip install requests
