name: run curl

on: 
  workflow_dispatch:
jobs:
  curl-run:
    name: curl command
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - run curl command
        run:
          curl -d "name=test" https://httpbin.org/post
