name: run python

on: push

jobs:
  python-code-run:
    name: python code test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - checkout code
        uses: actions/checkout@v4
        with: 
          repository: gsm34/test-actions
          ref: main
          path: splunk-api
      - name: custom - read csv and call splunk API
        run:
          python splunk-api/readfile.py
