name: run python

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  python-code-run:
    name: python code test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: custom - read csv and call splunk API
        run:
          python readfile.py
